language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
<<<<<<< HEAD
  - npm run build
  - test $TRAVIS_BRANCH = "master" && npm run deploy-storybook
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
=======
  - npm run test:prod && npm run build
>>>>>>> a5325f815057dc12ba2ab481ca691f64a58b06b8
after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release
