language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run build
  - test $TRAVIS_BRANCH = "master" && npm run deploy-storybook
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
